name: http_provider
description: Paquete para obtener informaciÃ³n de forma remota.
version: 1.0.12

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  dio: ^5.9.0
  fpdart: ^1.2.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.10.5
  freezed: ^3.2.3
  test: ^1.29.0
  very_good_analysis: ^10.0.0
